#spring.application.name=ledgerworks
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.application.name=ledgerworks

spring.datasource.url=jdbc:mysql://localhost:3306/ledgerworks
spring.datasource.username=root
spring.datasource.password=Ledger@2026

#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
jwt.secret=LedgerWorksSuperSecretKeyLedgerWorksSuperSecretKey123456
jwt.expiration=86400000


